app:
    host: localhost
    port: 3200
database:
    type: cockroachdb
    host: localhost
    port: 26257
    username: root
    password: mzg123
    database: mazongguan_dev
    logging: true
    synchronize: true